"""Constants for Ventilation Controller."""

DOMAIN = "ventilation_controller"
CONF_NAME = "name"
CONF_COOLING_MODE = "cooling_mode"
CONF_TEMP_SENSOR = "temp_sensor"
CONF_COVER_ENTITY = "cover_entity"
CONF_AC_CLIMATE_ENTITY = "ac_climate_entity"
CONF_AC_CONFLICT_PROTECTION = "ac_conflict_protection"
CONF_CO2_SENSOR = "co2_sensor"
CONF_CO2_VENTILATION = "co2_ventilation"
CONF_CO2_THRESHOLD = "co2_threshold"
CONF_CO2_HYSTERESIS = "co2_hysteresis"
CONF_CO2_VENTILATION_POSITION = "co2_ventilation_position"
CONF_CO2_NO_EFFECT_TIMEOUT = "co2_no_effect_timeout"
CONF_CO2_MINIMUM_DROP = "co2_minimum_drop"
CONF_CO2_INDOOR_GUARD_MARGIN = "co2_indoor_guard_margin"
CONF_CO2_COLD_OUTDOOR_THRESHOLD = "co2_cold_outdoor_threshold"
CONF_CO2_COLD_MAX_POSITION = "co2_cold_max_position"
CONF_EXHAUST_ENTITY = "exhaust_entity"
CONF_EXHAUST_MODE = "exhaust_mode"
CONF_EXHAUST_MIN_WINDOW_POSITION = "exhaust_min_window_position"
CONF_EXHAUST_NO_COOLING_TIMEOUT = "exhaust_no_cooling_timeout"
CONF_EXHAUST_MIN_TEMP_DROP = "exhaust_min_temp_drop"
CONF_EXHAUST_MAX_RUNTIME = "exhaust_max_runtime"
CONF_EXHAUST_COOLDOWN = "exhaust_cooldown"
CONF_EXHAUST_MANUAL_OVERRIDE_TIMEOUT = "exhaust_manual_override_timeout"
CONF_OUTDOOR_SENSOR = "outdoor_sensor"
CONF_TARGET_TEMP = "target_temp"
CONF_KP = "kp"
CONF_KI = "ki"
CONF_KD = "kd"
CONF_UPDATE_INTERVAL = "update_interval"
CONF_MIN_POSITION = "min_position"
CONF_MAX_POSITION = "max_position"
CONF_COOLING_DELTA_THRESHOLD = "cooling_delta_threshold"
CONF_COOLING_DELTA_HYSTERESIS = "cooling_delta_hysteresis"
CONF_TEMP_DEADBAND = "temp_deadband"
CONF_POSITION_CHANGE_THRESHOLD = "position_change_threshold"
CONF_PID_PROFILE = "pid_profile"

COOLING_MODE_DISABLED = "disabled"
COOLING_MODE_FORCE = "force"
COOLING_MODE_AUTO = "auto"

PID_PROFILE_MANUAL = "manual"
PID_PROFILE_SOFT = "soft"
PID_PROFILE_NORMAL = "normal"
PID_PROFILE_AGGRESSIVE = "aggressive"

DEFAULT_NAME = "Ventilation Controller"
DEFAULT_COOLING_MODE = COOLING_MODE_AUTO
DEFAULT_TARGET_TEMP = 24.0
DEFAULT_KP = 6.0
DEFAULT_KI = 3600.0
DEFAULT_KD = 0.0
DEFAULT_UPDATE_INTERVAL = 60
DEFAULT_MIN_POSITION = 0
DEFAULT_MAX_POSITION = 100
DEFAULT_AC_CONFLICT_PROTECTION = False
DEFAULT_CO2_VENTILATION = False
DEFAULT_CO2_THRESHOLD = 1000.0
DEFAULT_CO2_HYSTERESIS = 100.0
DEFAULT_CO2_VENTILATION_POSITION = 30.0
DEFAULT_CO2_NO_EFFECT_TIMEOUT = 10
DEFAULT_CO2_MINIMUM_DROP = 50.0
DEFAULT_CO2_INDOOR_GUARD_MARGIN = 0.3
DEFAULT_CO2_COLD_OUTDOOR_THRESHOLD = 5.0
DEFAULT_CO2_COLD_MAX_POSITION = 15.0
DEFAULT_EXHAUST_MODE = COOLING_MODE_DISABLED
DEFAULT_EXHAUST_MIN_WINDOW_POSITION = 30.0
DEFAULT_EXHAUST_NO_COOLING_TIMEOUT = 10
DEFAULT_EXHAUST_MIN_TEMP_DROP = 0.2
DEFAULT_EXHAUST_MAX_RUNTIME = 60
DEFAULT_EXHAUST_COOLDOWN = 15
DEFAULT_EXHAUST_MANUAL_OVERRIDE_TIMEOUT = 10
DEFAULT_COOLING_DELTA_THRESHOLD = 3.0
DEFAULT_COOLING_DELTA_HYSTERESIS = 1.0
DEFAULT_TEMP_DEADBAND = 0.5
DEFAULT_POSITION_CHANGE_THRESHOLD = 1.0
DEFAULT_PID_PROFILE = PID_PROFILE_NORMAL

PID_PROFILE_PRESETS = {
    PID_PROFILE_SOFT: {
        CONF_KP: 10.0,
        CONF_KI: 5400.0,
        CONF_KD: 0.0,
        CONF_POSITION_CHANGE_THRESHOLD: 2.0,
    },
    PID_PROFILE_NORMAL: {
        CONF_KP: DEFAULT_KP,
        CONF_KI: DEFAULT_KI,
        CONF_KD: DEFAULT_KD,
        CONF_POSITION_CHANGE_THRESHOLD: DEFAULT_POSITION_CHANGE_THRESHOLD,
    },
    PID_PROFILE_AGGRESSIVE: {
        CONF_KP: 4.0,
        CONF_KI: 1800.0,
        CONF_KD: 0.0,
        CONF_POSITION_CHANGE_THRESHOLD: 0.5,
    },
}
